# This workflow will build a React application, run tests, and push a Docker image to Docker Hub.
# For more information, visit: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: React App CI with Docker

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-docker:

    runs-on: ubuntu-latest

    steps:
    # Checkout the code from the repository
    - name: Checkout repository
      uses: actions/checkout@v4

    # Setup Node.js environment and cache dependencies
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version:  "0.1.0"
        cache: 'npm'

    # Set OpenSSL legacy provider for Node.js globally
    - name: Set NODE_OPTIONS environment variable
      run: echo "NODE_OPTIONS=--openssl-legacy-provider" >> $GITHUB_ENV

    # Install dependencies
    - name: Install dependencies
      run: npm ci

    # Build the React application
    - name: Build application
      run: npm run build

    # Run tests
    - name: Run tests
      run: npm test

    # Log in to Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Build Docker image
    - name: Build Docker image
      run: docker build -t ${{ secrets.DOCKER_USERNAME }}/react-app:latest .

    # Push Docker image to Docker Hub
    - name: Push Docker image
      run: docker push ${{ secrets.DOCKER_USERNAME }}/react-app:latest
