# This workflow will install dependencies, cache/restore them, build the source code, and run tests.
# For more information, visit: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    # Checkout the code from the repository
    - name: Checkout repository
      uses: actions/checkout@v4

    # Setup Node.js environment and cache dependencies
    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    # Install dependencies
    - name: Install dependencies
      run: npm ci

    # Build the application (if a build script exists in package.json)
    - name: Build application
      run: npm run build --if-present

    # Run tests
    - name: Run tests
      run: npm test

    # Cache Node.js modules for faster subsequent builds
    - name: Cache Node.js modules
      uses: actions/cache@v3
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ matrix.node-version }}-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-${{ matrix.node-version }}
          ${{ runner.os }}-node

    # Upload test results (optional, for advanced test reporting tools)
    # Uncomment the following lines if needed
    # - name: Upload test results
    #   uses: actions/upload-artifact@v3
    #   with:
    #     name: test-results
    #     path: test-results/
